const fs=require('fs'),path=require('path'),matter=require('gray-matter'),{marked}=require('marked');
const postsDir=path.join(__dirname,'content/posts'); const outDir=path.join(__dirname,'artigos'); fs.mkdirSync(outDir,{recursive:true});
const posts=fs.readdirSync(postsDir).filter(f=>f.endsWith('.md')).map(f=>{const raw=fs.readFileSync(path.join(postsDir,f),'utf8'),p=matter(raw);return {...p.data,slug:f.replace(/\.md$/,'') ,body:marked(p.content)}}).sort((a,b)=>new Date(b.date)-new Date(a.date));
const css=fs.readFileSync(path.join(__dirname,'styles.css'),'utf8');
const shell=(title,content)=>`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | ECCOLAB</title><meta name="description" content="${title}"><link rel="stylesheet" href="/styles.css"></head><body><header><div class="container"><nav><a class="brand" href="/">ECCO<span>LAB</span></a><div class="navlinks"><a href="/artigos.html">Artigos</a><a href="/sobre.html">Sobre</a><a class="btn primary" href="https://wa.me/5528999773655?text=Ol%C3%A1%2C%20vim%20pelo%20ECCOLAB%20e%20gostaria%20de%20saber%20sobre%20o%20atendimento.">Conversar</a></div></nav></div></header>${content}<footer><div class="container">© 2026 ECCOLAB · Psicanálise e Escuta</div></footer></body></html>`;
let cards=posts.map(p=>`<article class="card"><span class="tag">${p.category||'Reflexão'}</span><h3>${p.title}</h3><p>${p.description||''}</p><a class="read" href="/artigos/${p.slug}/">Ler artigo →</a></article>`).join('');
const list=`<main><section class="article-hero"><div class="container"><div class="eyebrow">Biblioteca ECCOLAB</div><h1>Artigos para pensar o que insiste.</h1><p class="lead">Psicanálise, psicologia analítica, filosofia, relações e experiência humana.</p></div></section><section class="section"><div class="container"><div class="grid">${cards}</div></div></section></main>`;
fs.writeFileSync(path.join(__dirname,'artigos.html'),shell('Artigos',list));
for(const p of posts){const article=`<main><section class="article-hero"><div class="container"><div class="eyebrow">${p.category||'Reflexão'}</div><h1>${p.title}</h1><p class="lead">${p.description||''}</p></div></section><div class="container article-layout"><article class="prose">${p.body}<div class="note">Este conteúdo é educativo e não substitui atendimento profissional.</div><p style="margin-top:30px"><a class="btn primary" href="https://wa.me/5528999773655?text=Ol%C3%A1%2C%20li%20o%20artigo%20${encodeURIComponent(p.title)}%20e%20gostaria%20de%20conversar%20sobre%20atendimento.">Conversar sobre atendimento →</a></p></article></div></main>`;const d=path.join(outDir,p.slug);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),shell(p.title,article));}
console.log(`Built ${posts.length} articles`);